export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const INCREASE_CART_ITEM = "INCREASE_CART_ITEM"
export const DECREASE_CART_ITEM = "DECREASE_CART_ITEM"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
